name: Generate TODO file
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate TODO file
      run: |
        ./tools/gen_todo.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "CI: Generated TODO file"
